apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        volumeMounts:
        - mountPath: "/var/www/html/Images"
          name: images            
        - mountPath: "/var/www/html/Annotations"
          name: annotations
      volumes:
        - name: images
          persistentVolumeClaim:
           claimName: imagesClaim
        - name: annotations
          persistentVolumeClaim:
            claimName: annotationsClaim
      resources:
{{ toYaml .Values.resources | indent 12 }}
